# Generated by Django 3.2.3 on 2021-09-13 13:20

from django.db import migrations, models
import django.db.models.deletion
import posts.utils


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0005_alter_post_user_posted'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='parent_video',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='audio_file', to='posts.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='file',
            field=models.FileField(blank=True, upload_to=posts.utils.upload_path_handler, validators=[posts.utils.file_size]),
        ),
    ]
