# Generated by Django 3.2.3 on 2021-10-12 18:32

from django.db import migrations, models
import posts.utils


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_tags'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='default.png', upload_to=posts.utils.upload_path_handler),
        ),
    ]
