# Generated by Django 3.2.3 on 2021-10-24 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_post_thumbnail'),
        ('posts', '0008_post_thumbnail'),
    ]

    operations = [
    ]
