# Generated by Django 3.2.3 on 2021-10-24 18:44

from django.db import migrations, models
import posts.utils


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0009_merge_0006_post_thumbnail_0008_post_thumbnail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='thumbnail',
            field=models.ImageField(default='default.png', upload_to=posts.utils.upload_path_handler),
        ),
    ]
