# Generated by Django 3.2.3 on 2021-09-17 15:23

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_profile_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='professions',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=100), blank=True, null=True, size=None),
        ),
    ]
