# Generated by Django 3.2.3 on 2021-07-19 12:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('room_id', models.CharField(max_length=40, primary_key=True, serialize=False, unique=True)),
                ('room_user_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_part_1', to=settings.AUTH_USER_MODEL)),
                ('room_user_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_part_2', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_message', models.CharField(max_length=400)),
                ('from_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_messages', to=settings.AUTH_USER_MODEL)),
                ('to_room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='room_messages', to='chat.room')),
            ],
        ),
    ]
