# Generated by Django 3.2.3 on 2021-07-19 13:58

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2021, 7, 19, 13, 58, 49, 899660, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
