# Generated by Django 3.2.3 on 2021-07-23 12:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('chat', '0002_message_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='room_user_1',
        ),
        migrations.RemoveField(
            model_name='room',
            name='room_user_2',
        ),
        migrations.AddField(
            model_name='room',
            name='room_users',
            field=models.ManyToManyField(related_name='rooms_in', to=settings.AUTH_USER_MODEL),
        ),
    ]
