# Generated by Django 3.2.3 on 2021-07-23 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20210723_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='group_name',
            field=models.CharField(blank=True, max_length=16),
        ),
        migrations.AddField(
            model_name='room',
            name='is_group',
            field=models.BooleanField(default=False),
        ),
    ]
